
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./backend/data/tp_node.sql:/docker-entrypoint-initdb.d/tp_node.sql
    ports:
      - "3307:3306"

  backend:
    build: ./backend
    restart: always
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
    volumes:
      - ./backend:/app
    working_dir: /app
    command: node index.js

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    # working_dir: /app
    # command: npm run dev

volumes:
  db_data:
