name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-backend:
    name: Lint Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      - name: Run ESLint on backend
        run: npm run lint
        working-directory: ./backend

  lint-frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run ESLint on frontend
        run: npm run lint
        working-directory: ./frontend

  test-unit:
    needs: lint-backend
    name: Test Unitaire
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Installer les dépendances backend
        run: npm install
        working-directory: ./backend

      - name: Fix jest permissions
        run: chmod +x ./backend/node_modules/.bin/jest

      - name: Lancer les tests unitaires
        run: npm run test-unit
        working-directory: ./backend

  test-integration:
    needs: [lint-backend, test-unit]
    name: Test d'Intégration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Créer le fichier .env.test à partir du secret
        run: echo "${{ secrets.ENV_TEST }}" > .env

      - name: Afficher le contenu du .env
        run: cat .env

      - name: Démarrer les services de test
        run: docker compose up -d --build db backend

      - name: Afficher l'état des conteneurs
        run: docker compose ps

      - name: Attendre que MySQL soit prêt dans le réseau Docker
        run: docker compose exec backend npx wait-port db:3306 -t 60000

      - name: Lancer les tests d'intégration
        run: docker compose exec backend npm run test-integration

      - name: Nettoyer les services après tests
        if: always()
        run: docker compose down --volumes
